title: Плюсник 9Д
titles:
  login: Вход в систему
  admin: Администрация
  sheet_editor: Редактор листков
  conduit_editor: Редактор плюсника
  edit_user_modal: Редактирование пользователя
  bulk_create_users_modal: Создание пользователей
navbar:
  index: Главная
  sheet_editor: Редактор листков
  sheet_viewer: Просмотр листков
  conduit_editor: Редактор плюсника
  admin: Администрация
  logout: Выйти
scopes:
  admin: Администрация сайта
  sheets_edit: Редактирование TeX файлов
  conduit_edit: Редактирование плюсника
  conduit_generation: Просмотр своего плюсника

user_category:
  admin: Администраторы
  teacher: Учителя
  student: Ученики

exceptions:
  invalid_credentials: Неверный логин или пароль!
  account_disabled: Ваша учетная запись заблокирована! Обратитесь к Сане.
  bad_jwt: Неверный токен доступа! Обратитесь к Сане.
  insufficient_scope: Недостаточно прав для выполнения операции!
  account_already_exists: Учетная запись с таким логином уже существует!

  latex_invariant_error: Не удалось реализовать инвариант компилятора! Обратитесь к Сане.
  latex_syntax_error: "Ошибка синтаксиса LaTeX: '%(message)s'"
  latex_semantic_error: "Семантическая ошибка при компиляции LaTeX: '%(message)s'"
  no_sheet_id: Не указан идентификатор листка! Установите при помощи '\sheetid{<id>}'.
  no_sheet_name: Не указано название листка! Установите при помощи '\sheetname{<id>}'.
  file_not_found: Файл '%(filename)s' не найден!
  latex_sheet_id_mismatch: Идентификатор листка в LaTeX не совпадает с ожидаемым! Ожидалось '%(expected)s', получено '%(actual)s'. Сохранение отменено для сохранения данных.
  no_latex_sheet: В файле '%(filename)s' нет LaTeX объекта!
  no_conduit: В файле '%(filename)s' нет кондуита!
  file_corrupted: Файл '%(filename)s' поврежден!
  invalid_conduit_data: Не удалось сохранить кондуит! Обратитесь к Сане.
  stacking_limit: Превышен лимит пост-командного спуска!
  unknown_node: Неизвестный блок на верхнем уровне - %(node)s (тип %(type)s)!
  invalid_argcount: Некорректное количество аргументов к команде %(name)d! Ожидалось %(expected)d, получено %(actual)d.
  invalid_env_argcount: Некорректное количество аргументов к окружению %(name)d! Ожидалось 0, получено %(actual)d.
  itemextract_error: Блоки \itemize и \enumerate должны начинаться с \item, а не с %(name)s!
  command_banned: Команда '%(name)s' запрещена! Используйте '%(instead)s' вместо нее.
  malformed_newcommand: Некорректное определение команды! Получено '%(actual)s'.
  nesting_limit: Превышен лимит вложенности команд (%(limit)i)!
  latex_big: LaTeX файл слишком большой! Ожидалось не более %(limit)i символов, получено %(actual)i.
  need_force_regen: Используется force стратегия перестройки кондуитов, но кондуит уже есть. Добавьте в документ '__FORCE_REGEN__'.

common:
  last_sheets: Последние листочки
  username: Имя пользователя
  password: Пароль
  btn_login: Войти
  btn_close: Закрыть
  btn_save: Сохранить
  sheet_in_use: Редактируется пользователем
  unsaved_changes: В файле есть несохранённые изменения! Используйте Ctrl+S, чтобы их сохранить, или нажмите на тот же листок ещё раз, чтобы их сбросить.

pages:
  index:
    login_for_full_access: Войдите в систему для полного доступа к сайту.
    logged_in_as: "Вы вошли в систему как %(name)s. Ваши права доступа:"
  admin:
    bulk_create_howto: Укажите одно имя на строку. Для каждого нового пользователя, который ещё не существует, к имени будут добавлены логин и пароль.
    btn_edit_user: Редактировать
    btn_reset_password: Сбросить пароль
    btn_bulk_create_users: Создать пользователей
    switch_teachers: Создание учителей
    edit_login: Логин
    edit_username: Имя пользователя
    edit_privileges: Права доступа
    error_updating_privileges: "Произошла ошибка при редактировании прав доступа: "
    new_password: "Новый пароль: "
    error_resetting_password: "Произошла ошибка при сбросе пароля: "
    error_bulk_creating: "Произошла ошибка при создании пользователей: "
    user_login: "Логин: <code>%s</code><br /> привилегии:"

  sheet_editor:
    delete_dangerous: Нажмите на эту кнопку ещё раз, чтобы удалить листок.
    delete_sheet: Если вы точно хотите удалить листок, введите здесь его номер/ID.
    warning_found: "Компилятор выдал предупреждения при сохранении: "
    btn_add_sheet: Создать листок
    btn_remove_sheet: Удалить листок
    missing_cache_strategy: "Следующие задачи пропали из листка: %s. Кондуит не был сгенерирован."
  conduit:
    submit_date: "Дата сдачи: "
    teacher: "Принимающий: "
    editor: "Оценку выставил "
    set_for: Выставляю за
    successfully_saved: Кондуит сохранён!
    error_while_saving: "Произошла ошибка при сохранении кондуита: "
