name: Deploy to the website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Website Deploy
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://conduit.179.ru/internal/update'
          method: 'POST'
          bearerToken: ${{ secrets.DEPLOYMENT_KEY }}
          timeout: 30000
